### PR TITLE
Perhaps you should stop using shitty packages for what can be inlined.

### PR DESCRIPTION
**Pull request by paulmillr**

### CODE REVIEW

**Comment by paulmillr** [comment]
You've broke YARN: https://github.com/yarnpkg/yarn/issues/3851

**Comment by omnidan** [comment]
thank you @paulmillr - however this breaks in certain cases: https://github.com/omnidan/node-emoji/pull/41#discussion_r119728915

even the test is failing now

**Comment by paulmillr** [comment]
Feel free to adjust my PR.

**Comment by omnidan** [comment]
@paulmillr I reverted the PR that broke this and released `1.6.1` - yarn should work again now.

**Comment by omnidan** [comment]
However this is *not* a simple fix and we decided to use lodash toArray because it has a special behavior with emoji that one liners didn't have.

If you can come up with a way to do this without the dependency - would be good to know :grin:

**Comment by targumon** [comment]
@paulmillr I guess you used that language because you got pissed after your productivity was probably affected.
Don't get me wrong - I cuss around my computer too, just not in commit messages of public repositories... ;-)

**Pull request closed without merging**
