### PR TITLE
Added emoji13.1

### PR DESCRIPTION
**Pull request by junpayment**
emojifile.js corresponding to Emoji 13.1 was required for this addition.

However, in the `js-emoji` referenced by this repository, emojifile.js corresponding to Emoji 13.1 did not exist yet.
https://github.com/iamcal/js-emoji/blob/master/lib/emoji.js#L645

So I had to create it.
The procedure is shown below.

### 1. Fetch emoji file

I modified this script to fetch 13.1 and output version information.
https://github.com/amio/emoji.json/blob/master/scripts/gen.js

gen.js
```js
const fs = require('fs')
const path = require('path')
const https = require('https')

const EMOJI_VERSION = '13.1'

main()

async function main () {
  const text = await getTestFile(EMOJI_VERSION)

  console.log(`Format text to json...`)
  const collected = text.trim().split('\n').reduce((accu, line) => {
    if (line.startsWith('# group: ')) {
      console.log(`  Processing ${line.substr(2)}...`)
      accu.group = line.substr(9)
    } else if (line.startsWith('# subgroup: ')) {
      accu.subgroup = line.substr(12)
    } else if (line.startsWith('#')) {
      accu.comments = accu.comments + line + '\n'
    } else {
      const meta = parseLine(line)
      if (meta) {
        meta.category = `${accu.group} (${accu.subgroup})`
        meta.group = accu.group
        meta.subgroup = accu.subgroup
        accu.full.push(meta)
        accu.compact.push(meta.char)
      } else {
        accu.comments = accu.comments.trim() + '\n\n'
      }
    }
    return accu
  }, { comments: '', full: [], compact: [] })

  console.log(`Processed emojis: ${collected.full.length}`)

  console.log('Write file: emoji.json, emoji-compact.json \n')
  await writeFiles(collected)

  console.log(collected.comments)
}

async function getTestFile (ver) {
  const url = `https://unicode.org/Public/emoji/${ver}/emoji-test.txt`

  process.stdout.write(`Fetch emoji-test.txt (v${EMOJI_VERSION})`)
  return new Promise((resolve, reject) => {
    https.get(url, res => {
      let text = ''
      res.setEncoding('utf8')
      res.on('data', (chunk) => {
        process.stdout.write('.')
        text += chunk
      })
      res.on('end', () => {
        process.stdout.write('\n')
        resolve(text)
      })
      res.on('error', reject)
    })
  })
}

function parseLine (line) {
  const data = line.trim().split(/\s+[;#] /)

  if (data.length !== 3) {
    return null
  }

  const [ codes, status, charAndName ] = data
  const [ , char, version, name ] = charAndName.match(/^(\S+) E(\d+\.\d+) (.+)$/)

  return { codes, char, name, version }
}

const rel = (...args) => path.resolve(__dirname, ...args)

function writeFiles({ full, compact }) {
  fs.writeFileSync(rel('../emoji.json'), JSON.stringify(full), 'utf8')
  fs.writeFileSync(rel('../emoji-compact.json'), JSON.stringify(compact), 'utf8')
}
```

And ran.

```sh
node gen.js
```

This will output ʻemoji.json`.

### 2. Create 13. 1 emojifile.js

Next, I output emojifile.js by narrowing down to 13.1 with the following script.
I referred to here. Thank you very much.
https://github.com/omnidan/node-emoji/issues/95#issuecomment-670311266

convert.js
```js
const convert = (emojiString, alias) => {
  const key = [...emojiString].map(s => {
    return s.codePointAt(0).toString(16).padStart(4, 0)
  }).join('-')

  let value = ''
  for (let i = 0; i < emojiString.length; i++) {
    const code = emojiString[i].codePointAt(0).toString(16).padStart(4, 0)
    value += '\\u' + code.toUpperCase()
  }

  console.log(`"${key}":[["${value}"],"","",["${alias}"]],`)
}

const emojiList = require('./emoji.json')
const list = emojiList.map(data => {
  const key = data.name.replace(/,|:/, '').split(/\s+/).join('-')
  return {char: data.char, key: key}
})

list.forEach(d => convert(d.char, d.key))
```

And ran.

```sh
node convert.js > emojifile_13.1
```

### 3. Add to emojifile.js

Next, I pasted the contents of emojifile_13.1 into the description of emojifile.js.

---
Since we just added the 13.1 description to the existing description, it should not affect the existing functionality.

Also, since the key is described in a hyphen case, it should be possible to handle the case where the key is added corresponding to 13.1 in `js-emoji` in the future.

Thanks the great product.

### CODE REVIEW

**Comment by Richienb** [comment]
> Will be fixed in https://github.com/amio/emoji.json/pull/21 for node-emoji v2

**Comment by junpayment** [comment]
@Richienb 
Thanks a lot.

I checked the change diffs in `emoji.json/scripts/gen.js`.
As a result, it was the same as the contents of `lib/emojifile.js` of this PR.

**Comment by maxlk** [comment]
@junpayment @Richienb @omnidan Is something blocking this PR from being merged?

**Review by dantehemerson — APPROVED** [review]
Can anyone merge this please

**Comment by junpayment** [comment]
@maxlk
nothing.

@dantehemerson 
I'm  not  a contributor. Please merge this PR.

**Comment by Dhanraj-Naik** [comment]
Hi i am getting :waving_black_flag: when i add flag-england(🏴󠁧󠁢󠁥󠁮󠁧󠁿) or flag-scotland(🏴󠁧󠁢󠁳󠁣󠁴󠁿) or flag-wales(🏴󠁧󠁢󠁷󠁬󠁳󠁿) when i unemojify.
so again when i do emojify that :waving_black_flag: string, i am getting following output:
OUTPUT: 🏴?????????????????????????.

Why 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁳󠁣󠁴󠁿 flags are not decoded even if their codes are mentioned in emojifile.js?

**Comment by junpayment** [comment]
@Dhanraj-Naik 
Did the event occur in this commit?
Could you show me the source code at that time?

**Comment by Dhanraj-Naik** [comment]
@junpayment 
Hi, i noticed that the **node-emoji** uses lodash method **toArray** method for splitting emoji to unicode that is creating that issue.
So i tried some cases with 

1.  Normal text,
2.  Commonly used emojis and 
3.  Latest emojis like (🏴󠁧󠁢󠁥󠁮󠁧󠁿 , 🏴󠁧󠁢󠁳󠁣󠁴󠁿 ), and noticed following output.

**_please check screenshots for the same._**
Screenshot 2021-03-14 at 3 32 01 PM
Screenshot 2021-03-14 at 3 32 57 PM
Screenshot 2021-03-14 at 3 34 15 PM

**Comment by junpayment** [comment]
@Dhanraj-Naik 
I understand, but shouldn't it be a separate issue?
Or isn't it a problem of emoji clustering of loadash?

**Comment by Dhanraj-Naik** [comment]
@junpayment i agree with you.
At first i thought its the problem with emoji package.
Then after digging deep, i realized that its problem with lodash package used internally in emoji package to split emoji into their respective code.
I just wanted to know if there are any fixes coming for such emojis.
thanks

**Comment by junpayment** [comment]
It seems to be merged emoji13.1 in the below PR.
https://github.com/omnidan/node-emoji/pull/110

**Pull request closed without merging**
