### PR TITLE
Fix flag identification bug: `Emoji.which(🇲🇽)`

### PR DESCRIPTION
**Pull request by smeijer**
Fix the flag issue from PR #21 

---
This test now turns green.

```js
    it("should work for flags", function() {
      var mexico = emoji.which('🇲🇽');
      should.exists(mexico);
      mexico.should.be.exactly('flag-mx');

      var marocco = emoji.which('🇲🇦');
      should.exists(marocco);
      marocco.should.be.exactly('flag-ma');
      
      // see issue #21
      mexico.should.not.equal(marocco);
    });
```

### CODE REVIEW

**Comment by omnidan** [comment]
@smeijer looks good! 👌 can you add a test case for `unemojify` with flags too?

**Comment by smeijer** [comment]
Sure thing. Will add it later today.

**Comment by omnidan** [comment]
Thank you so much!

**Comment by omnidan** [comment]
Do you think you are going to be able to make a PR for #16 soon? If yes then I will wait and make a release once it's merged :grin:

**Comment by smeijer** [comment]
I'll start working in #16, and submit a pr within 2 / 3 days. But you'll possibly have some feedback on it, as I'll also refactor the hash table a bit for performance improvements. 

So for you to decide if you want to wait for it.

**Comment by omnidan** [comment]
@smeijer that's alright, if it's within a week I'll wait for a release :ok_hand:

**Comment by omnidan** [comment]
@smeijer thank you so much for all the contributions btw! :tada:

**Comment by smeijer** [comment]
You're welcome. Turned out I had some time to spend today; So I'll submitting 3 PR's.

**Pull request merged**
