### PR TITLE
Check char codes instead of chars

### PR DESCRIPTION
**Pull request by jackiehluo**
Ran into a weird situation where I was replacing emoji in text using a regex, and the characters didn't match (but were clearly the same emoji, with the same code point and char code). Thought it might be safer to check this way.

### CODE REVIEW

**Comment by omnidan** [comment]
@jackiehluo Thanks for the PR! That surely is strange behaviour :confused: Can you add a failing test that only passes with this PR merged, but not with the current node-emoji version?

**Comment by jackiehluo** [comment]
Thanks for replying so quickly! Not sure how to run the test suite, so let me know if that fails... `"☔" === "☔️"` is false, so that fails in the current version but not with the PR.

**Comment by omnidan** [comment]
@jackiehluo it's simply `npm run test` :wink:

**Comment by jackiehluo** [comment]
Ooh, got it. Cool!

**Comment by jackiehluo** [comment]
And... apparently some emoji share the same char codes. Code points should be safe!

**Comment by omnidan** [comment]
@jackiehluo Ah yeah, I think it's because emoji consist of multiple char codes. `codePointAt` should be fine, although the build is failing, can you check that? ` TypeError: Object 💯 has no method 'codePointAt'`

**Comment by jackiehluo** [comment]
Hm, I can't reproduce that error. It's passing for me locally. Does you get that error?

screen shot 2016-04-08 at 10 46 36 am

**Comment by omnidan** [comment]
@jackiehluo The tests do pass for me, however, I'm on node v5.7.0, the build server is on node v0.10.44. I think [`.codePointAt`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt) was added in ES2015, which is why we'll need to include a polyfill to make it work on older versions ([maybe this one?](https://github.com/mathiasbynens/String.prototype.codePointAt))

**Comment by jackiehluo** [comment]
Ahhh, I clearly don't know much about JavaScript. Cool! Looks like it's working now.

**Comment by omnidan** [comment]
@jackiehluo thanks a lot :grin: Sorry to bother you again, but can you add another test case that checks if `"☔" === "☔️"`? Then it'll be perfect :ok_hand:

**Comment by jackiehluo** [comment]
Not sure what you mean by that. A full test case for that or just an assertion to check it in that test?

**Comment by omnidan** [comment]
@jackiehluo You can revert the last commit, that is always true (`('☔').should.not.equal('☔️');`), I meant a full test case on `emoji.which('☔') === emoji.which('☔️')` :blush:

**Comment by jackiehluo** [comment]
Ohhh, that makes sense. Added!

**Comment by omnidan** [comment]
Cool, thanks a lot :+1:

**Comment by omnidan** [comment]
@jackiehluo I published [`1.3.0`](https://github.com/omnidan/node-emoji/releases/tag/v1.3.0) with this change :grin: Thanks again!

**Comment by jackiehluo** [comment]
Yay, perfect! Thank you!

**Pull request merged**
