### PR TITLE
Updated emoji data to v3.2.2 of js-emoji

### PR DESCRIPTION
**Pull request by laurent22**

### CODE REVIEW

**Comment by omnidan** [comment]
@laurent22 CI is failing (the test with `umbrella`). there are two different emoji:

- ☔️  - `:umbrella:` on github
- ☂️  -`:open_umbrella:` on github

maybe we should keep the current `umbrella` as ☔️  for backwards compatibility and consistency with github emoji short codes?

**Comment by laurent22** [comment]
@omnidan, yes that would be fine for me. How are these special cases handled normally? Maybe in emojiparse.js we could add some check like `if (name === 'open_umbrella') continue;` or something like this?

**Comment by sidbatra** [comment]
Hi @laurent22 and @omnidan this looks fantastic can we merge it in please? I was looking for the clinking glasses emoji and stumbled across this. Anything I can do to help?

**Comment by omnidan** [comment]
@sidbatra as I mentioned before, I would like to keep `umbrella` backwards compatible (and compatible with the github emoji short codes), so this needs to be adjusted in the parser or the emoji file directly.

**Comment by omnidan** [comment]
we have #61 now

**Pull request closed without merging**
