### PR TITLE
Don't return blank when the emoji is unknow

### PR DESCRIPTION
**Pull request by ahanriat**
Thanks a lot for your work !
I've just changed the behaviour when the emoji is not found, it now returns the token instead of `''` allowing it with custom emoji ;)

### CODE REVIEW

**Comment by omnidan** [comment]
@ahanriat thanks a lot! there is a small typo, though: it should be `unknown`, not `unknow`

**Comment by ahanriat** [comment]
It should be ok now 😉

**Comment by omnidan** [comment]
@ahanriat thanks a lot! :ok_hand:

**Comment by omnidan** [comment]
released 1.0.4 with this

**Comment by ahanriat** [comment]
Awesome, thanks for your reactivity !! :smile:

**Comment by omnidan** [comment]
Thank *you* for your PR :grin:

**Pull request merged**
