### PR TITLE
Add `files` to `package.json`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Saves ~2.5 KB when published to NPM.

### CODE REVIEW

**Comment by omnidan** [comment]
@wtgtybhertgeghgtwtg Thanks for the PR! Doesn't this mean that `index.js` will be excluded? If yes, the `main` field will need to be adjusted too.

**Comment by wtgtybhertgeghgtwtg** [comment]
I can't believe I forgot that, thank you so much for catching it.  Would you prefer `index.js` to be included or `main` to point to `lib/emoji`, in which case `index.js` can be deleted?

**Comment by omnidan** [comment]
@wtgtybhertgeghgtwtg pointing `main` to `lib/emoji.js` directly would probably be the best way to go about this, then `index.js` can be deleted

**Comment by omnidan** [comment]
Thank you :grin:

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for merging.  Sorry it took four commits to get it right.

**Comment by omnidan** [comment]
no problem :wink: released `1.4.2` with this change

**Pull request merged**
