### PR TITLE
Added missing fencer 🤺 emoji

### PR DESCRIPTION
**Pull request by laurent22**
Added missing fencer 🤺 emoji

### CODE REVIEW

**Comment by omnidan** [comment]
@laurent22 is this the only emoji that is missing? I think there are a couple from the new set that this library does not support yet. would you be willing to add all of them to this PR? :grin:

**Comment by laurent22** [comment]
@omnidan, yes I've noticed that 🛒 is also missing, but I don't know actually what the new set is. Do you have any information about this? Basically what's currently in node-emoji and what might be missing? I can give it a try and see if I can create a PR will all of them then.

**Comment by omnidan** [comment]
@laurent22 you can find the original list on https://github.com/omnidan/node-emoji/blob/master/lib/emojifile.js - which is the file that the .json gets generated from. I got the emoji data from https://github.com/iamcal/js-emoji/blob/master/lib/emoji.js, which might have an updated list now.

**Comment by laurent22** [comment]
Ok it's done in #60 I've done a few tests and can see that the old emojis are still converted and the new ones too. I've only found this one that still doesn't seem to be supported: 🏋 but maybe it will be part of the next js-emoji update.

**Comment by omnidan** [comment]
Thanks! Let's continue in #60 then :grin:

**Pull request closed without merging**
