### PR TITLE
adds coverage report

### PR DESCRIPTION
**Pull request by gabrielcsapo**
> output 

```
> istanbul cover _mocha test



  emoji.js
    ✓ should return an emoji code
    get(emoji)
      ✓ should return an emoji code
      ✓ should support github flavored markdown emoji
    random()
      ✓ should return a random emoji and the corresponding key
    which(emoji_code)
      ✓ should return name of the emoji
      ✓ should work for differently formed characters
      ✓ should return the same name for differently formed characters
    emojify(str)
      ✓ should parse :emoji: in a string and replace them with the right emoji
      ✓ should leave unknown emoji
      ✓ should replace unknown emoji using provided cb function


  10 passing (13ms)

=============================================================================
Writing coverage object [/Users/gabrielcsapo/Documents/temp/node-emoji/coverage/coverage.json]
Writing coverage reports at [/Users/gabrielcsapo/Documents/temp/node-emoji/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 32/32 )
Branches     : 92.86% ( 13/14 )
Functions    : 100% ( 6/6 )
Lines        : 100% ( 31/31 )
================================================================================
```

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
thoughts @omnidan?

**Comment by omnidan** [comment]
Sorry for the late response, I am quite busy recently :wink:

Thanks for the PR, looks good :smile:

**Comment by gabrielcsapo** [comment]
Yay! Thanks @omnidan!

**Comment by gabrielcsapo** [comment]
Thoughts on using coveralls?

**Comment by omnidan** [comment]
@gabrielcsapo I just set it up, but it seems to take a while to update: https://coveralls.io/github/omnidan/node-emoji

**Comment by gabrielcsapo** [comment]
Awesome! @omnidan

**Pull request merged**
