### PR TITLE
Resolved issue Directions to use emoji with - in their name #116

### PR DESCRIPTION
**Pull request by ritikbanger**
Resolved issue Directions to use emoji with - in their name #116

### CODE REVIEW

**Comment by ritikbanger** [comment]
cc @omnidan

**Comment by ritikbanger** [comment]
Any update on this @omnidan

**Comment by omnidan** [comment]
hi @ritikbanger - sorry for the late reply! I think in general we should encourage using `.get()` instead of directly accessing emoji from the library, it's more of an internal way they are accessed. Also, your PR changed the general formatting of the README.

Please only add a note that `.get()` should be used instead of accessing emoji directly, and do not change the rest of the formatting.

**Comment by ritikbanger** [comment]
> hi @ritikbanger - sorry for the late reply! I think in general we should encourage using `.get()` instead of directly accessing emoji from the library, it's more of an internal way they are accessed. Also, your PR changed the general formatting of the README.
> 
> Please only add a note that `.get()` should be used instead of accessing emoji directly, and do not change the rest of the formatting.

It is fixed.

**Comment by omnidan** [comment]
@ritikbanger `emoji['name']` to access emoji directly should not be used as it is an internal API and might change in future versions, please encourage using `emoji.get('name')` instead, there `t-rex` will also work fine.

**Comment by ritikbanger** [comment]
any update on this?

**Comment by omnidan** [comment]
@ritikbanger Thank you!

**Pull request merged**
